  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/en/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/en/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/en/portfolio/"
