name: blog

on:
  push:
    tags:
      - doc*
    branches: [main]
  pull_request:
    branches: [main, "doc/*"]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build ⚙️
        working-directory: ${{ github.workspace }}
        run: hugo --minify --baseUrl=https://daniel-iel.github.io/Blog/

      - name: Deploy ✉️
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/doc')
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: "${{ github.workspace }}/public"
